### ISSUE TITLE
表里有可为空的字段，更新时怎么区分要更新的列？

### ISSUE THREAD

**Issue by ZhangYueqiu** [hexu6788/HSQL#1]

**Comment by hexu6788** [comment]
不赋值就行了。如表 t_student 共有 id,name,age,birthday,school_id 5个字段。想把年龄为16岁的学生的全部放到school_id 为 2 的学校。  sql是这么写， update t_student set shcool_id = 2 where age = 16;
在 HSQL是这么写 database.Update<Student>(x=>x.Age = 16,new Student(){ SchoolId = 2})

**Comment by hexu6788** [comment]
resolved
